ZeroEfforts_RMS/urls.py
from django.contrib import admin
from django.urls import path, include

# Changing the orignal admin protal
admin.site.site_header = "ZERO EFFORTS"
admin.site.site_title = "ZERO EFFORTS Admin Portal"
admin.site.index_title = "Welcome to ZERO EFFORTS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('about/', views.about, name="about"),
    #path('', include('inventory.urls')),
    path('', include('account.urls')),
    path('inventory/', include('inventory.urls')),
    # path('manufacturer/', include('manufacturer.urls')),
    path('category/', include('category.urls')),
    path('customer/', include('customer.urls')),
    # path('order/', include('order.urls')),
    # path('warehouse/', include('warehouse.urls')),
    # path('store/', include('store.urls')),
    path('sale/', include('sale.urls')),
    path('stock/', include('stock.urls')),
    # path('purchase/', include('purchase.urls')),
    # path('staff/', include('staff.urls')),

    #third party
    # path("select2/", include("django_select2.urls"))
]

category/urls.py
from django.urls import path
from . import views

app_name = "category"
urlpatterns = [
    path('', views.category, name="category"),
    path('create/', views.categoryCreate, name="category-create"),
    path('<int:pk>/', views.categoryDetail, name="category-detail"),
    path('<int:pk>/update/', views.categoryUpdate, name="category-update"),
    path('<int:pk>/delete/', views.categoryDelete, name="category-delete"),
]

sale/urls.py
from django.urls import path
from . import views

app_name = "sale"
urlpatterns = [
    path('', views.sale, name="sale"),
    path('create/', views.saleCreate, name="sale-create"),
    path('<int:pk>/', views.saleDetail, name="sale-detail"),
    path('<int:pk>/update/', views.saleUpdate, name="sale-update"),
    path('<int:pk>/delete/', views.saleDelete, name="sale-delete"),
]

category/models.py
from django.db import models
from django.shortcuts import reverse
from simple_history.models import HistoricalRecords

# Create your models here.


class Category(models.Model):

    name = models.CharField(
        max_length=50, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    createdDate = models.DateTimeField(auto_now_add=True)
    history= HistoricalRecords()


    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category:category-detail", kwargs={"pk": self.pk})

category/forms.py
from django import forms
from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

category/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category
from .forms import CategoryForm
# Create your views here.


def category(request):
    categories = Category.objects.all()
    return render(request, 'category/category.html', {'items': categories})


def categoryCreate(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category:category')

    context = {
        'name': 'Add Category',
        'form': form,
    }
    return render(request, 'form_snippet.html', context)


def categoryDetail(request, pk):
    category = get_object_or_404(Category, id=pk)
    return render(request, 'category/category_detail.html', {'item': category})


def categoryUpdate(request, pk):
    categories = get_object_or_404(Category, id=pk)
    form = CategoryForm(instance=categories)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=categories)
        if form.is_valid():
            form.save()
            return redirect('category:category')

    context = {
        'name': 'Edit Category',
        'form': form,
    }
    return render(request, 'form_snippet.html', context)


def categoryDelete(request, pk):
    categories = get_object_or_404(Category, id=pk)
    if request.method == "POST":
        categories.delete()
        return redirect('category:category')

    context = {
        'item': categories,
        'delete_url': 'category:category-delete',
        'return_url': 'category:category'
    }
    return render(request, 'delete_snippet.html', context)

category/templates/category/category.html
{% extends 'base.html'%}
{% load static %}

{% block extrastyle %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrastyle %}


{% block body %}

{% comment %} <br>
<div class="row">
  <div class="col">
    <div class="card card-body">
      <form method="get">
        <br>
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>
<br> {% endcomment %}

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="d-sm-flex align-items-center justify-content-between ">
      <h3 class="m-0 font-weight-bold text-primary">Categories</h3>
      <a href="{% url 'category:category-create'%}"
        class="d-none d-sm-inline-block shadow-sm btn btn-primary btn-icon-split">
        <span class="icon text-white-50">
<i class="fas fa-plus-square"></i>
        </span>
        <span class="text">Add</span>
      </a>
    </div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </tfoot>
        <tbody>
          {% for item in items %}
          <tr class='clickable-row' href="#"
            onclick="document.location = '{% url 'category:category-detail' item.id %}';">
            <td>{{item.name}}</td>
            <td>{{item.description}}</td>
            <td>
              <a href="{% url 'category:category-detail' item.id %}" class="btn btn-info btn-sm">
                <i class="fas fa-info-circle"></i>
              </a>
              <a href="{% url 'category:category-update' item.id %}" class="btn btn-primary btn-sm">
                <i class="fas fa-edit"></i>
              </a>
              <a href="{% url 'category:category-delete' item.id %}" class="btn btn-danger btn-sm">
                <i class="fas fa-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock body %}

{% block extrajavascript %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock extrajavascript %}

category/templates/category/category_detail.html
{%  extends 'base.html' %}

{% block body_content %}

	<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Category: {{ item.name }}</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'category:category-update' item.id %}">Update Customer</a>
			<a class="btn btn-outline-danger  btn-sm btn-block" href="{% url 'category:category-delete' item.id %}">Delete Customer</a>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Detail</h5>
			<hr>
			<p>Date Created: {{ item.createdDate }}</p>
			<p>Description: {{ item.description }}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px"></h1>
		</div>
	</div>
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>

			</table>
		</div>
	</div>
</div>
 
{% endblock body_content %}