ZeroEfforts_RMS/urls.py
from django.contrib import admin
from django.urls import path, include

# Changing the orignal admin protal
admin.site.site_header = "ZERO EFFORTS"
admin.site.site_title = "ZERO EFFORTS Admin Portal"
admin.site.index_title = "Welcome to ZERO EFFORTS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('about/', views.about, name="about"),
    #path('', include('inventory.urls')),
    path('', include('account.urls')),
    path('inventory/', include('inventory.urls')),
    # path('manufacturer/', include('manufacturer.urls')),
    path('category/', include('category.urls')),
    path('customer/', include('customer.urls')),
    # path('order/', include('order.urls')),
    # path('warehouse/', include('warehouse.urls')),
    # path('store/', include('store.urls')),
    path('sale/', include('sale.urls')),
    path('stock/', include('stock.urls')),
    # path('purchase/', include('purchase.urls')),
    # path('staff/', include('staff.urls')),

    #third party
    # path("select2/", include("django_select2.urls"))
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('create/', views.inventoryCreate, name="inventory-create"),
    path('<int:pk>/', views.inventoryDetail, name="inventory-detail"),
    path('<int:pk>/update/', views.inventoryUpdate, name="inventory-update"),
    path('<int:pk>/delete/', views.inventoryDelete, name="inventory-delete"),
]

sale/urls.py
from django.urls import path
from . import views

app_name = "sale"
urlpatterns = [
    path('', views.sale, name="sale"),
    path('create/', views.saleCreate, name="sale-create"),
    path('<int:pk>/', views.saleDetail, name="sale-detail"),
    path('<int:pk>/update/', views.saleUpdate, name="sale-update"),
    path('<int:pk>/delete/', views.saleDelete, name="sale-delete"),
]

stock/urls.py
from django.urls import path, include
from . import views

app_name = "stock"
urlpatterns = [
    path('', views.stock, name="stock"),
    path('create/', views.stockCreate, name="stock-create"),
    path('<int:pk>/', views.stockDetail, name="stock-detail"),
    path('<int:pk>/update/', views.stockUpdate, name="stock-update"),
    path('<int:pk>/delete/', views.stockDelete, name="stock-delete"),
    # path('inventory/', include('inventory.urls', namespace="inventory"), name="inventory"),
]

stock/models.py
from django.db import models
from store.models import Store
from inventory.models import Inventory
# Create your models here.


class Stock(models.Model):
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE)
    inventory = models.ForeignKey(
        Inventory, on_delete=models.CASCADE)
    quantity = models.IntegerField(
        null=False, blank=False, default=0)

    class Meta:
        verbose_name = "Stock"
        verbose_name_plural = "Stocks"
        unique_together=['store', 'inventory']

    def __str__(self):
        return (self.store.name+" | "+self.inventory.name)

    def get_absolute_url(self):
        return reverse("inventory:inventory-detail", kwargs={"pk": self.pk})

stock/forms.py
from django import forms
from .models import Stock
class StockForm(forms.ModelForm):
    
    class Meta:
        model = Stock
        fields = "__all__"

stock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Stock
from .forms import StockForm
# Create your views here.


def stock(request):
    stocks = Stock.objects.all()
    return render(request, 'stock/stock.html', {'items': stocks})


def stockCreate(request):
    form = StockForm()
    if request.method == 'POST':
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('stock:stock')

    context = {'form': form}
    return render(request, 'form_snippet.html', context)


def stockDetail(request, pk):
    stock = get_object_or_404(Stock, id=pk)
    return render(request, 'stock/stock_detail.html', {'item': stock})


def stockUpdate(request, pk):
    cust = get_object_or_404(Stock, id=pk)
    form = StockForm(instance=cust)
    if request.method == 'POST':
        form = StockForm(request.POST, instance=cust)
        if form.is_valid():
            form.save()
            return redirect('stock:stock')

    context = {'form': form}
    return render(request, 'form_snippet.html', context)


def stockDelete(request, pk):
    cust = get_object_or_404(Stock, id=pk)
    if request.method == "POST":
        cust.delete()
        return redirect('stock:stock')

    context = {
        'item': cust,
        'delete_url': 'stock:stock-delete',
        'return_url': 'stock:stock'
    }
    return render(request, 'delete_snippet.html', context)

stock/templates/stock/stock.html
{% extends 'base.html'%}
{% load static %}

{% block extrastyle %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrastyle %}


{% block body %}

{% comment %} <br>
<div class="row">
  <div class="col">
    <div class="card card-body">
      <form method="get">
        <br>
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>
<br> {% endcomment %}

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="d-sm-flex align-items-center justify-content-between ">
      <h3 class="m-0 font-weight-bold text-primary">Stock</h3>
      <a href="{% url 'stock:stock-create'%}"
        class="d-none d-sm-inline-block shadow-sm btn btn-primary btn-icon-split">
        <span class="icon text-white-50">
<i class="fas fa-plus-square"></i>
        </span>
        <span class="text">Add</span>
      </a>
    </div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Store</th>
            <th>Inventory</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Store</th>
            <th>Inventory</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </tfoot>
        <tbody>
          {% for item in items %}
          <tr class='clickable-row' href="#"
            onclick="document.location = '{% url 'inventory:inventory-detail' item.inventory.id %}';">
            <td>{{item.store}}</td>
            <td>{{item.inventory}}</td>
            <td>{{item.quantity}}</td>
            <td>
              <a href="{% url 'inventory:inventory-detail' item.inventory.id %}" class="btn btn-info btn-sm">
                <i class="fas fa-info-circle"></i>
              </a>
              <a href="{% url 'stock:stock-update' item.id %}" class="btn btn-primary btn-sm">
                <i class="fas fa-edit"></i>
              </a>
              <a href="{% url 'stock:stock-delete' item.id %}" class="btn btn-danger btn-sm">
                <i class="fas fa-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock body %}

{% block extrajavascript %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock extrajavascript %}