ZeroEfforts_RMS/urls.py
from django.contrib import admin
from django.urls import path, include

# Changing the orignal admin protal
admin.site.site_header = "ZERO EFFORTS"
admin.site.site_title = "ZERO EFFORTS Admin Portal"
admin.site.index_title = "Welcome to ZERO EFFORTS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('about/', views.about, name="about"),
    #path('', include('inventory.urls')),
    path('', include('account.urls')),
    path('inventory/', include('inventory.urls')),
    # path('manufacturer/', include('manufacturer.urls')),
    path('category/', include('category.urls')),
    path('customer/', include('customer.urls')),
    # path('order/', include('order.urls')),
    # path('warehouse/', include('warehouse.urls')),
    # path('store/', include('store.urls')),
    path('sale/', include('sale.urls')),
    path('stock/', include('stock.urls')),
    # path('purchase/', include('purchase.urls')),
    # path('staff/', include('staff.urls')),

    #third party
    # path("select2/", include("django_select2.urls"))
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('create/', views.inventoryCreate, name="inventory-create"),
    path('<int:pk>/', views.inventoryDetail, name="inventory-detail"),
    path('<int:pk>/update/', views.inventoryUpdate, name="inventory-update"),
    path('<int:pk>/delete/', views.inventoryDelete, name="inventory-delete"),
]

sale/urls.py
from django.urls import path
from . import views

app_name = "sale"
urlpatterns = [
    path('', views.sale, name="sale"),
    path('create/', views.saleCreate, name="sale-create"),
    path('<int:pk>/', views.saleDetail, name="sale-detail"),
    path('<int:pk>/update/', views.saleUpdate, name="sale-update"),
    path('<int:pk>/delete/', views.saleDelete, name="sale-delete"),
]

inventory/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import get_object_or_404
from manufacturer.models import Manufacturer
from category.models import Category
# Create your models here.


class Inventory(models.Model):
    name = models.CharField(
        max_length=50, null=False, blank=False, unique=True)
    price = models.FloatField(
        null=False, blank=False)
    manufacturer = models.ForeignKey(
        Manufacturer, on_delete=models.DO_NOTHING, null=True, blank=True)
    category = models.ManyToManyField(
        Category, null=True, blank=True)
    description = models.TextField(
        null=True, blank=True)
    createdDate = models.DateTimeField(auto_now_add=True)
    updatedDate = models.DateTimeField(auto_now=True)
    createdBy = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='%(class)s_product_created')
    updatedBy = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='%(class)s_product_updated')

    class Meta:
        verbose_name = "Inventory"
        verbose_name_plural = "Inventories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventory:inventory-detail", kwargs={"pk": self.pk})

inventory/forms.py
from django import forms
from .models import Inventory
from store.models import Store


class InventoryForm(forms.ModelForm):
    store = forms.ModelChoiceField(queryset=Store.objects.all())
    quantity=forms.IntegerField()

    class Meta:
        model = Inventory
        fields = "__all__"
    

inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Inventory
from .forms import InventoryForm
from stock.forms import StockForm
from stock.models import Stock
# Create your views here.


def inventory(request):
    inventories = Inventory.objects.all()
    stocks = Stock.objects.all()
    context = {
        'items': inventories
    }
    return render(request, 'inventory/inventory.html', context)


def inventoryCreate(request):
    form = InventoryForm()
    if request.method == 'POST':
        form = InventoryForm(request.POST)
        if form.is_valid():
            # Check for same name and store inventory
            # Stock.objects.get(
            #     inventory=Inventory.objects.get(
            #         name=form.cleaned_data['name']),
            #     store=form.cleaned_data['store'],
            # )
            # print(same)
            # return
            
            newInventory=form.save()
            Stock.objects.create(
                store=form.cleaned_data['store'],
                inventory=newInventory,
                quantity=form.cleaned_data['quantity']
            )
            return redirect('inventory:inventory')

    context={'form': form}
    return render(request, 'form_snippet.html', context)


def inventoryDetail(request, pk):
    inventory=get_object_or_404(Inventory, id=pk)
    return render(request, 'inventory/inventory_detail.html', {'item': inventory})


def inventoryUpdate(request, pk):
    cust=get_object_or_404(Inventory, id=pk)
    form=InventoryForm(instance=cust)
    if request.method == 'POST':
        form=InventoryForm(request.POST, instance=cust)
        if form.is_valid():
            form.save()
            return redirect('inventory:inventory')

    context={'form': form}
    return render(request, 'form_snippet.html', context)


def inventoryDelete(request, pk):
    cust=get_object_or_404(Inventory, id=pk)
    if request.method == "POST":
        cust.delete()
        return redirect('inventory:inventory')

    context={
        'item': cust,
        'delete_url': 'inventory:inventory-delete',
        'return_url': 'inventory:inventory'
    }
    return render(request, 'delete_snippet.html', context)

inventory/templates/inventory/inventory.html
{% extends 'base.html'%}
{% load static %}
{% load inventory_extras %}

{% block extrastyle %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrastyle %}


{% block body %}

{% comment %} <br>
<div class="row">
  <div class="col">
    <div class="card card-body">
      <form method="get">
        <br>
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>
<br> {% endcomment %}

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="d-sm-flex align-items-center justify-content-between ">
      <h3 class="m-0 font-weight-bold text-primary">Inventory</h3>
      <a href="{% url 'inventory:inventory-create'%}"
        class="d-none d-sm-inline-block shadow-sm btn btn-primary btn-icon-split">
        <span class="icon text-white-50">
<i class="fas fa-plus-square"></i>
        </span>
        <span class="text">Add</span>
      </a>
    </div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </tfoot>
        <tbody>
          {% for item in items %}
          <tr class='clickable-row' href="#"
            onclick="document.location = '{% url 'inventory:inventory-detail' item.id %}';">
            <td>{{item.name}}</td>
                        <td>{{item.price}}</td>
                        <td>{{item|get_quantity}}</td>
            <td>
              <a href="{% url 'inventory:inventory-detail' item.id %}" class="btn btn-info btn-sm">
                <i class="fas fa-info-circle"></i>
              </a>
              <a href="{% url 'inventory:inventory-update' item.id %}" class="btn btn-primary btn-sm">
                <i class="fas fa-edit"></i>
              </a>
              <a href="{% url 'inventory:inventory-delete' item.id %}" class="btn btn-danger btn-sm">
                <i class="fas fa-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% endblock body %}

{% block extrajavascript %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock extrajavascript %}

inventory/templates/inventory/inventory_detail.html
{%  extends 'base.html' %}

{% block body_content %}

	<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Inventory: {{ item.name }}</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'inventory:inventory-update' item.id %}">Update Customer</a>
			<a class="btn btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:inventory-delete' item.id %}">Delete Customer</a>
		</div>
		<br>
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px"></h1>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Price: {{ item.price }}</p>
			<p>Manufacturer: {{ item.manufacturer }}</p>
			<p>Category: {{ item.category }}</p>
			<p>Description: {{ item.decription }}</p>
			<p>Created Date: {{ item.createdDate }}</p>
			<p>Updated Date: {{ item.updatedDate }}</p>
		</div>
	</div>

	
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
		<h5>Recent Orders of {{ item.name }}</h5>
			<table class="table table-sm">
				<tr>
					<th>ID</th>
					<th>Category</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>

			</table>
		</div>
	</div>
</div>
 
{% endblock body_content %}