ZeroEfforts_RMS/urls.py
from django.contrib import admin
from django.urls import path, include

# Changing the orignal admin protal
admin.site.site_header = "ZERO EFFORTS"
admin.site.site_title = "ZERO EFFORTS Admin Portal"
admin.site.index_title = "Welcome to ZERO EFFORTS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('about/', views.about, name="about"),
    #path('', include('inventory.urls')),
    path('', include('account.urls')),
    path('inventory/', include('inventory.urls')),
    # path('manufacturer/', include('manufacturer.urls')),
    path('category/', include('category.urls')),
    path('customer/', include('customer.urls')),
    # path('order/', include('order.urls')),
    # path('warehouse/', include('warehouse.urls')),
    # path('store/', include('store.urls')),
    path('sale/', include('sale.urls')),
    path('stock/', include('stock.urls')),
    # path('purchase/', include('purchase.urls')),
    # path('staff/', include('staff.urls')),

    #third party
    # path("select2/", include("django_select2.urls"))
]

account/urls.py
from django.urls import path
from . import views

app_name="account"
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('detail/', views.detail, name="account-detail"),
]

category/urls.py
from django.urls import path
from . import views

app_name = "category"
urlpatterns = [
    path('', views.category, name="category"),
    path('create/', views.categoryCreate, name="category-create"),
    path('<int:pk>/', views.categoryDetail, name="category-detail"),
    path('<int:pk>/update/', views.categoryUpdate, name="category-update"),
    path('<int:pk>/delete/', views.categoryDelete, name="category-delete"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('create/', views.inventoryCreate, name="inventory-create"),
    path('<int:pk>/', views.inventoryDetail, name="inventory-detail"),
    path('<int:pk>/update/', views.inventoryUpdate, name="inventory-update"),
    path('<int:pk>/delete/', views.inventoryDelete, name="inventory-delete"),
]

sale/urls.py
from django.urls import path
from . import views

app_name = "sale"
urlpatterns = [
    path('', views.sale, name="sale"),
    path('create/', views.saleCreate, name="sale-create"),
    path('<int:pk>/', views.saleDetail, name="sale-detail"),
    path('<int:pk>/update/', views.saleUpdate, name="sale-update"),
    path('<int:pk>/delete/', views.saleDelete, name="sale-delete"),
]

stock/urls.py
from django.urls import path, include
from . import views

app_name = "stock"
urlpatterns = [
    path('', views.stock, name="stock"),
    path('create/', views.stockCreate, name="stock-create"),
    path('<int:pk>/', views.stockDetail, name="stock-detail"),
    path('<int:pk>/update/', views.stockUpdate, name="stock-update"),
    path('<int:pk>/delete/', views.stockDelete, name="stock-delete"),
    # path('inventory/', include('inventory.urls', namespace="inventory"), name="inventory"),
]

templates/base.html
{% comment %}
var - title
var - pageheading
block - body
block - extrahead
block - extrajavascript
block - extrastyle
{% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ZeroEfforts - {{ title }}</title>

  {% block extrahead %}
  {% endblock extrahead %}

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this page -->
  {% block extrastyle %}
  {% endblock extrastyle %}

</head>

<body id="page-top" class="sidebar-toggled">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'account:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ZeroEfforts</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Navbar -->
      {% include 'navbar.html' %}

      <!-- Begin Page Content -->
      <div class="container-fluid">

        <!-- Page Heading -->
        {% if pageheading %}
        <h1 class="h3 mb-4 text-gray-800">{{pageheading}}</h1>
        {% endif %}

        {% block body %}
        {% endblock body %}

      </div>
      <!-- /.container-fluid -->

  </div>
  <!-- End of Main Content -->


  <!-- Footer -->
  {% include 'footer.html' %}

  </div>
  <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'account:login' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Extra JavaScript -->

  {% block extrajavascript %}
  {% endblock extrajavascript %}


</body>

</html>

templates/base_old.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %} Bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> 
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script> 

    {% comment %} Font Awesome {% endcomment %}
    <script src="{% static 'fontawesome/js/all.min.js' %}"></script>

    {% comment %} MDBootstrap {% endcomment %}
    {% comment %} <!-- Font Awesome -->
    <link href="{% static 'fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'mdbootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design for Bootstrap -->
    <link href="{% static 'mdbootstrap/css/mdb.min.css' %}" rel="stylesheet"> {% endcomment %}
    {% comment %} MDBootstrap {% endcomment %}
    {% comment %} <!-- jQuery -->
    <script src="{% static 'mdbootstrap/js/jquery-3.3.1.min.js' %}"></script>
    <!-- Popper.js -->
    <script src="{% static 'mdbootstrap/js/popper.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'mdbootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Material Design for Bootstrap -->
    <script src="{% static 'mdbootstrap/js/mdb.min.js' %}"></script> {% endcomment %}

    {% block extra_style %}
    {% endblock extra_style %}

    <title>{% block title %}{% endblock %} | ZeroEfforts</title>

    {% include 'navbar.html' %}


</head>
<body>
    {% comment %} Bootstrap {% endcomment %}
    


    

    


    {% block body_content %}
    {% endblock body_content %}

    {% include 'footer.html' %}
</body>
</html>

templates/base_old2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">



    {% block extra_style %}
    {% endblock extra_style %}

    <style>

        body {
            background-color: #ebeff5;
        }

    </style>

    <title>{% block title %}{% endblock %} | ZeroEfforts</title>

    {% if show_navbar is not None %}
    {% else %}
    {% include 'navbar.html' %}
    {% endif %}



</head>

<body>
    {% comment %} Bootstrap {% endcomment %}








    {% block body_content %}
    {% endblock body_content %}

    {% include 'footer.html' %}

    <script>
        $('select').selectpicker();
        {% comment %} $('select').fieldWrapper(); {% endcomment %}
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
</body>

</html>

templates/delete_snippet.html
{% extends 'base.html' %}

{% comment %} {% block title %}
{{form | to_class_name}}
{% endblock title %} {% endcomment %}

{% block body_content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">

            <p>Are you sure you want to delete "{{item}}"?</p>

            <form action="" method="POST">

                {% csrf_token %}
                <input class="btn btn-warning" type="button" value="Cancel" onClick="javascript:history.go(-1);">

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock body_content %}

templates/footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>
        Copyright &copy; Zero Efforts 2020
        &emsp;
        |
        &emsp;
        Phone# 03076288887 waseem wala
        &emsp;
        |
        &emsp;
        zeroefforts.dev@gmail.com
      </span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

templates/form_snippet.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block body %}

<div class="card shadow mb-4 ">
  <div class="card-header py-3">
    <h3 class="m-0 font-weight-bold text-primary">{{name}}</h3>
  </div>
  <div class="card-body">
    <form action="" method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {{ field.errors }}
        <div class="col-4 col-form-label" style="padding: 0px; margin: 0px">
          {{ field.label_tag }}
        </div>
        <div class="col-8" style="padding: 0px; margin: 0px">
          {% render_field field class+="form-control" %}
        </div>
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
      {% endfor %}
      <br>
      <button name="submit" type="submit" class="btn btn-primary">{{name}}</button>

    </form>
  </div>
</div>

{% endblock body %}

templates/navbar.html
<!-- Nav Item - Dashboard -->
<li class="nav-item active">
  <a class="nav-link" href="{% url 'account:index' %}">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
  Interface
</div>

<!-- Nav Item - Sale Collapse Menu -->
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSales" aria-expanded="true"
    aria-controls="collapseSales">
    <i class="fas fa-users"></i>
    <span>Sales</span>
  </a>
  <div id="collapseSales" class="collapse" aria-labelledby="headingSales" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <a class="collapse-item" href="{% url 'sale:sale' %}">View Sales</a>
      <a class="collapse-item" href="{% url 'sale:sale-create' %}">Add Sale</a>

    </div>
  </div>
</li>

<!-- Nav Item - Customer Collapse Menu -->
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCustomers" aria-expanded="true"
    aria-controls="collapseCustomers">
    <i class="fas fa-users"></i>
    <span>Customers</span>
  </a>
  <div id="collapseCustomers" class="collapse" aria-labelledby="headingCustomers" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <a class="collapse-item" href="{% url 'customer:customer' %}">View Customers</a>
      <a class="collapse-item" href="{% url 'customer:customer-create' %}">Add Customer</a>

    </div>
  </div>
</li>

<!-- Nav Item - Inventory Collapse Menu -->
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventory" aria-expanded="true"
    aria-controls="collapseInventory">
    <i class="fas fa-boxes"></i>
    <span>Inventory</span>
  </a>
  <div id="collapseInventory" class="collapse" aria-labelledby="headingInventory" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <a class="collapse-item" href="{% url 'inventory:inventory' %}">View Inventory</a>
      <a class="collapse-item" href="{% url 'inventory:inventory-create' %}">Add Inventory</a>
      <a class="collapse-item" href="{% url 'stock:stock' %}">Stock</a>
    </div>
  </div>
</li>

<!-- Nav Item - Category Collapse Menu -->
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCategory" aria-expanded="true"
    aria-controls="collapseCategory">
<i class="fas fa-stream"></i>
    <span>Category</span>
  </a>
  <div id="collapseCategory" class="collapse" aria-labelledby="headingCategory" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <a class="collapse-item" href="{% url 'category:category' %}">View Categories</a>
      <a class="collapse-item" href="{% url 'category:category-create' %}">Add Category</a>
    </div>
  </div>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
  Addons
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
    aria-controls="collapsePages">
    <i class="fas fa-fw fa-folder"></i>
    <span>Pages</span>
  </a>
  <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
    <div class="bg-white py-2 collapse-inner rounded">
      <h6 class="collapse-header">Login Screens:</h6>
      <a class="collapse-item" href="login.html">Login</a>
      <a class="collapse-item" href="register.html">Register</a>
      <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
      <div class="collapse-divider"></div>
      <h6 class="collapse-header">Other Pages:</h6>
      <a class="collapse-item" href="404.html">404 Page</a>
      <a class="collapse-item" href="blank.html">Blank Page</a>
    </div>
  </div>
</li>

<!-- Nav Item - Charts -->
<li class="nav-item">
  <a class="nav-link" href="charts.html">
    <i class="fas fa-fw fa-chart-area"></i>
    <span>Charts</span></a>
</li>

<!-- Nav Item - Tables -->
<li class="nav-item">
  <a class="nav-link" href="tables.html">
    <i class="fas fa-fw fa-table"></i>
    <span>Tables</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

<!-- Sidebar Toggler (Sidebar) -->
<div class="text-center d-none d-md-inline">
  <button class="rounded-circle border-0" id="sidebarToggle"></button>
</div>

</ul>
<!-- End of Sidebar -->

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

  <!-- Main Content -->
  <div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

      <!-- Sidebar Toggle (Topbar) -->
      <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
      </button>

      <!-- Topbar Search -->
      <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
          <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
            aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search fa-sm"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Topbar Navbar -->
      <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
          <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
          </a>
          <!-- Dropdown - Messages -->
          <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
            <form class="form-inline mr-auto w-100 navbar-search">
              <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                  aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <!-- Counter - Alerts -->
            <span class="badge badge-danger badge-counter">3+</span>
          </a>
          <!-- Dropdown - Alerts -->
          <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">
              Alerts Center
            </h6>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-primary">
                  <i class="fas fa-file-alt text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 12, 2019</div>
                <span class="font-weight-bold">A new monthly report is ready to download!</span>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-success">
                  <i class="fas fa-donate text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 7, 2019</div>
                $290.29 has been deposited into your account!
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="mr-3">
                <div class="icon-circle bg-warning">
                  <i class="fas fa-exclamation-triangle text-white"></i>
                </div>
              </div>
              <div>
                <div class="small text-gray-500">December 2, 2019</div>
                Spending Alert: We've noticed unusually high spending for your account.
              </div>
            </a>
            <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
          </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <!-- Counter - Messages -->
            <span class="badge badge-danger badge-counter">7</span>
          </a>
          <!-- Dropdown - Messages -->
          <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">
              Message Center
            </h6>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                <div class="status-indicator bg-success"></div>
              </div>
              <div class="font-weight-bold">
                <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.
                </div>
                <div class="small text-gray-500">Emily Fowler · 58m</div>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                <div class="status-indicator"></div>
              </div>
              <div>
                <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent
                  to you?</div>
                <div class="small text-gray-500">Jae Chun · 1d</div>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                <div class="status-indicator bg-warning"></div>
              </div>
              <div>
                <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far,
                  keep up the good work!</div>
                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
              </div>
            </a>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                <div class="status-indicator bg-success"></div>
              </div>
              <div>
                <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say
                  this to all dogs, even if they aren't good...</div>
                <div class="small text-gray-500">Chicken the Dog · 2w</div>
              </div>
            </a>
            <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
          </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
            <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
          </a>
          <!-- Dropdown - User Information -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
              <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
              Profile
            </a>
            <a class="dropdown-item" href="#">
              <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
              Settings
            </a>
            <a class="dropdown-item" href="#">
              <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
              Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              Logout
            </a>
          </div>
        </li>

      </ul>

    </nav>
    <!-- End of Topbar -->